### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jonschlinkert** [jonschlinkert/template#31]
Big changes coming to template! https://github.com/jonschlinkert/template/tree/complete-refactor?files=1

**Comment by jonschlinkert** [comment]
@tunnckocore, have you seen this branch yet? Curious what your thoughts are

**Comment by tunnckoCore** [comment]
Ohh, i will, sounds cool!

**Comment by jonschlinkert** [comment]
@doowb / @tunnckoCore, what's not to like about this:

```js
app.engine('md', require('engine-lodash'))
  .data({ title: 'My Blog!' })
  .create('post');

glob({ gitignore: true })
  .readdirStream('test/fixtures/**/*.md')
  .on('data', function (file) {
    app.posts(file.path, file);
  })
  .on('end', function () {
    app.posts.forOwn(function (view, key) {
      view.render(function (err, res) {
        console.log(res.content);
      });
    });
  });`
```

Even better...

```js
var path = require('path');
var matter = require('parser-front-matter');
var glob = require('glob-fs');
var App = require('..');
var app = new App();

/**
 * streams
 */

// parse front matter
app.onLoad(/\.md$/, function (view, next) {
  matter.parse(view, next);
});

// register an engine...
app.engine('md', require('engine-lodash'));

// create custom view-collections
app.create('post')
  .create('list', {
    renameKey: function (fp) {
      return path.basename(fp, path.extname(fp));
    }
  });

// define "global" data
app.data({ title: 'My Blog!' });

// load a template onto the `list` collection
app.list('index.md', {
  content: 'My Posts!\n{{#each pagination.items}}{{locals.title}}\n{{/each}}\n',
  locals: {
    limit: 2,
    permalinks: {structure: ':collection/:num.html'}
  }
});

var index = app.lists.get('index');
var opts = {permalink: 'blog/posts/:collection/:num.html'};

// glob some templates onto the `post` collection
glob({ gitignore: true })
  .readdirStream('test/fixtures/**/*.md')
  .on('data', function (file) {
    app.posts(file.path, file);
  })
  .on('end', function () {
    app.posts
      .sortBy('data.title')
      .paginate(index, opts, function (err, posts) {
        posts.forEach(function (post) {
          post.render(function (err, post) {
            console.log(post.permalink(post.data.pagination));
          });
        });
      });
  });
```

**Comment by jonschlinkert** [comment]
and this: https://github.com/jonschlinkert/template/blob/complete-refactor/examples/pagination-groups.js#L121-L140. that's awesome @doowb lol. nice work

**Comment by tunnckoCore** [comment]
Is `v0.17.0-prop` branch continues to be the latest on which you work, guys? Or `complete-refactor` branch?

**Comment by jonschlinkert** [comment]
https://github.com/jonschlinkert/template/tree/0.17.0-prep is the latest. we're about to merge to master though. just trying to clean up

**Comment by tunnckoCore** [comment]
@jonschlinkert consider use `jstransformer` under the hood instead `engine-cache`?

**1.** 130+ transformers available (template engines, parsers and etc), tested and covered
**2.** almost always 8 methods available - [see the full PR'ed api docs](https://github.com/tunnckoCore/jstransformer#api)
**3.** fallbacks out of the box
**4.** sync, async and promise support

And it's pretty awesome, because you there have fallbacks. Say you have transformer in which you are only implemented `.compile` method, jstransformer handles that and expose 8 to the user - compile, compileAsync, compileFile, compileFileAsync, render, renderAsync, renderFile and renderFileAsync. 

Or say, you have only `.render` implemented, again.. all of them are available to the user. 

`*Async` methods returns promise if not callback given.

***

Also we have db with mappings https://github.com/jstransformers/inputformat-to-jstransformer, which allows the user to just type one desired type and it will return transformer which is installed.

Let's concentrate on [dictionary.json#L90-L98](https://github.com/jstransformers/inputformat-to-jstransformer/blob/master/dictionary.json#L90-L98) and this example, from the readme

```js
var jstransformer = require('jstransformer')
var inputFormatToTransformer = require('inputformat-to-jstransformer')

var md = inputFormatToTransformer('md')
// => remarkable, markdown, markdown-it, commonmark, or supermarked

jstransformer(md).render('# Hello World!').body
// => '<h1>Hello World!</h1>'
```

and will use first available from the list which is installed.

***

This mappings would be useful. Let's say

```js
var app = require('template')()

// would be just needed to install one of the jstransformers
// which is in the `hbs` category from `inputformat-to-jstransformer` list
app.engine('hbs')

// or
app.engine('css', require('jstransformer-opalcss'))

// or
app.engine('html', require('engine-lodash'))


app.create('page')

app.page('example.md', '{{= title }}')

// just `*File*` methods would read/write from/to disk
app.renderFileAsync('example.md', {title: 'foo bar'}, function (err, view) {
  // err, view
})

// rendered content of `example.md` 
var content = app.renderFile('example.md', {title: 'hello example'})

// view object, because the glob
var view = app.renderFile('articles/*.md', {title: 'bar baz qux'})

```

**Comment by jonschlinkert** [comment]
you can already use js-transformers with Template. engine-cache allows you to use js-transformers, or consolidate or any other application you want.
